[package]
name = "rmc-minimal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
env_logger.workspace = true
log.workspace = true
rmc-core = { workspace = true }
rmc-stats.workspace = true
rand.workspace = true
rand_distr.workspace = true
